[package]
name = "hexagony"
version = "0.1.0"
authors = ["Ryan Lowe"]
edition = "2018"

[dependencies]
clap = { version = "2.33", default-features = false }
rug = { version = "1.12", default-features = false, features = ["integer"] }
